CREATE TABLE covid_us
(
  id serial NOT NULL,
  state varchar(2),
positive numeric(8,0),
positiveScore numeric(8,0),
negativeScore numeric(8,0),
negativeRegularScore numeric(8,0),
commercialScore numeric(8,0),
grade varchar(2),
score numeric(8,0),
notes varchar(200),
dataQualityGrade varchar(2),
negative numeric(8,0),
pending numeric(8,0),
hospitalizedCurrently numeric(8,0),
hospitalizedCumulative numeric(8,0),
inIcuCurrently numeric(8,0),
inIcuCumulative numeric(8,0),
VentilatorCurrently numeric(8,0),
onVentilatorCumulative numeric(8,0),
recovered numeric(8,0),
lastUpdateEt varchar(20),
checkTimeEt varchar(20),
death numeric(8,0),
hospitalized numeric(8,0),
total numeric(8,0),
totalTestResults numeric(8,0),
posNeg numeric(8,0),
fips varchar(2),
dateModified varchar(20),
dateChecked varchar(20),
hash varchar(40),
  CONSTRAINT persons_pkey PRIMARY KEY (state)
)

